import group1 from "assets/images/group-icons/1.png";
import group2 from "assets/images/group-icons/2.png";
import group3 from "assets/images/group-icons/3.png";
import group4 from "assets/images/group-icons/4.png";
import group5 from "assets/images/group-icons/5.png";
import group6 from "assets/images/group-icons/6.png";
import { ISignalGroup } from "types/global";

export const myGroups: ISignalGroup[] = [
  {
    name: "ABC 15",
    avatar: group1,
    groupType: "Private",
    minAllocation: 100,
    maxAllocation: 1000,
    subscriptionType: "Free",
    revenue: { month: 1000 },
    totalMembers: 78,
    connectionRequest: 5,
    activeEmails: [
      "johnryan@gmail.com",
      "jonathanwhite@gmail.com",
      "macryenoldsjean@gmail.com",
      "josephjacobjudah@gmail.com",
    ],
  },
  {
    name: "The Champions",
    avatar: group2,
    groupType: "Public",
    minAllocation: 200,
    maxAllocation: 2000,
    subscriptionType: "Premium",
    revenue: { month: 1300 },
    totalMembers: 71,
    connectionRequest: 2,
    activeEmails: [
      "jonathanwhite@gmail.com",
      "johnryan@gmail.com",
      "josephjacobjudah@gmail.com",
      "macryenoldsjean@gmail.com",
    ],
  },
  {
    name: "Bloom Group",
    avatar: group3,
    groupType: "Public",
    minAllocation: 2100,
    maxAllocation: 10000,
    subscriptionType: "Free",
    revenue: { month: 11000 },
    totalMembers: 28,
    connectionRequest: 1,
    activeEmails: [
      "johnryan@gmail.com",
      "jonathanwhite@gmail.com",
      "josephjacobjudah@gmail.com",
      "macryenoldsjean@gmail.com",
    ],
  },
  {
    name: "SHA 145",
    avatar: group4,
    groupType: "Private",
    minAllocation: 800,
    maxAllocation: 900,
    subscriptionType: "Premium",
    revenue: { month: 400 },
    totalMembers: 44,
    connectionRequest: 0,
    activeEmails: [
      "josephjacobjudah@gmail.com",
      "jonathanwhite@gmail.com",
      "johnryan@gmail.com",
      "macryenoldsjean@gmail.com",
    ],
  },
  {
    name: "ETDA Gurus",
    avatar: group5,
    groupType: "Private",
    minAllocation: 390,
    maxAllocation: 8000,
    subscriptionType: "Free",
    revenue: { month: 8000 },
    totalMembers: 94,
    connectionRequest: 12,
    activeEmails: [
      "johnryan@gmail.com",
      "macryenoldsjean@gmail.com",
      "josephjacobjudah@gmail.com",
      "jonathanwhite@gmail.com",
    ],
  },
  {
    name: "Req Group",
    avatar: group6,
    groupType: "Public",
    minAllocation: 10,
    maxAllocation: 100,
    subscriptionType: "Free",
    revenue: { month: 700 },
    totalMembers: 62,
    connectionRequest: 5,
    activeEmails: [
      "macryenoldsjean@gmail.com",
      "johnryan@gmail.com",
      "jonathanwhite@gmail.com",
      "josephjacobjudah@gmail.com",
    ],
  },
];

export const otherGroups: ISignalGroup[] = [
  {
    name: "ETDA Gurus",
    avatar: group5,
    groupType: "Private",
    minAllocation: 390,
    maxAllocation: 8000,
    subscriptionType: "Free",
    revenue: { month: 8000 },
    totalMembers: 94,
    connectionRequest: 12,
    activeEmails: [
      "johnryan@gmail.com",
      "macryenoldsjean@gmail.com",
      "josephjacobjudah@gmail.com",
      "jonathanwhite@gmail.com",
    ],
  },

  {
    name: "Bloom Group",
    avatar: group3,
    groupType: "Public",
    minAllocation: 2100,
    maxAllocation: 10000,
    subscriptionType: "Free",
    revenue: { month: 11000 },
    totalMembers: 28,
    connectionRequest: 1,
    activeEmails: [
      "johnryan@gmail.com",
      "jonathanwhite@gmail.com",
      "josephjacobjudah@gmail.com",
      "macryenoldsjean@gmail.com",
    ],
  },
  {
    name: "ABC 15",
    avatar: group1,
    groupType: "Private",
    minAllocation: 100,
    maxAllocation: 1000,
    subscriptionType: "Free",
    revenue: { month: 1000 },
    totalMembers: 78,
    connectionRequest: 5,
    activeEmails: [
      "johnryan@gmail.com",
      "jonathanwhite@gmail.com",
      "macryenoldsjean@gmail.com",
      "josephjacobjudah@gmail.com",
    ],
  },
  {
    name: "SHA 145",
    avatar: group4,
    groupType: "Private",
    minAllocation: 800,
    maxAllocation: 900,
    subscriptionType: "Premium",
    revenue: { month: 400 },
    totalMembers: 44,
    connectionRequest: 0,
    activeEmails: [
      "josephjacobjudah@gmail.com",
      "jonathanwhite@gmail.com",
      "johnryan@gmail.com",
      "macryenoldsjean@gmail.com",
    ],
  },

  {
    name: "Req Group",
    avatar: group6,
    groupType: "Public",
    minAllocation: 10,
    maxAllocation: 100,
    subscriptionType: "Free",
    revenue: { month: 700 },
    totalMembers: 62,
    connectionRequest: 5,
    activeEmails: [
      "macryenoldsjean@gmail.com",
      "johnryan@gmail.com",
      "jonathanwhite@gmail.com",
      "josephjacobjudah@gmail.com",
    ],
  },
  {
    name: "The Champions",
    avatar: group2,
    groupType: "Public",
    minAllocation: 200,
    maxAllocation: 2000,
    subscriptionType: "Premium",
    revenue: { month: 1300 },
    totalMembers: 71,
    connectionRequest: 2,
    activeEmails: [
      "jonathanwhite@gmail.com",
      "johnryan@gmail.com",
      "josephjacobjudah@gmail.com",
      "macryenoldsjean@gmail.com",
    ],
  },
];
